# Modification along rffontenelle/python-docs-pt-br
name: Update translations

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/update.yml'
      - 'scripts/update.sh'
    branches:
      - '!3.?'
      - '!2.7'
  # schedule:
  #   - cron: '0 23 * * *'

env:
  CPYTHON_BRANCH: '3.10'
  LANGUAGE: 'ja'

jobs:
  update:
    # Job to pull translation from Transifex platform, and commit & push changes
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v2
      - name: Check out CPython
        uses: actions/checkout@v2
        with:
          repository: python/cpython
          persist-credentials: false
          ref: ${{ env.CPYTHON_BRANCH }}
          path: cpython
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'


  merge:
    # Merge translations previously updated into older branches to make sure
    # older versions of Python Docs gets translated as well.
    # 'overwrite=true' means strings previously translated will get overwritten;
    # other branches will preserve translated strings, only filling in new
    # translations.
    name: merge into ${{ matrix.branch }}
    needs: [update]
    strategy:
      matrix:
        branch: [ 3.9, 3.8, 3.7, 3.6, 2.7 ]
        include:
          - branch: 3.9
            overwrite: true
    runs-on: ubuntu-latest
    steps:
      - name: Get current branch name
        shell: bash
        run:
          echo "CURRENT_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - name: Check out source branch (${{ env.CURRENT_BRANCH }})
        uses: actions/checkout@v1
        with:
          path: ${{ env.CURRENT_BRANCH }}
      - name: Check out target branch (${{ matrix.branch }})
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
          path: ${{ matrix.branch }}
